New spec to catch when non-JSON errors given
Spec now fails as intended:

```
 Failure/Error: expect { @cli.verify }.to raise_error(SystemExit)
       expected SystemExit, got #<NoMethodError: undefined method `status' for #<String:0x007f80e3a2c590>> with backtrace:
         # ./lib/tugboat/middleware/authentication_middleware.rb:24:in `rescue in call'
         # ./lib/tugboat/middleware/authentication_middleware.rb:20:in `call'
         # ./lib/tugboat/middleware/check_credentials.rb:11:in `call'
         # ./lib/tugboat/middleware/inject_client.rb:33:in `call'
         # ./lib/tugboat/middleware/check_configuration.rb:19:in `call'
         # ./lib/tugboat/middleware/inject_configuration.rb:10:in `call'
         # ./lib/tugboat/cli.rb:49:in `verify'
         # ./spec/cli/verify_cli_spec.rb:26:in `block (4 levels) in <top (required)>'
         # ./spec/cli/verify_cli_spec.rb:26:in `block (3 levels) in <top (required)>'
```