Removes wrong help messages for `images`.
To show all images, tugboat suggested to run `tugboat images list --global`.
However this returned following error message:

```sh
ERROR: tugboat images was called with arguments ["list"]
Usage: "tugboat images [OPTIONS]".
```

Because calling `tugboat images --global` did return all the images,
this commit removes the invalid `list` argument.